### ISSUE TITLE
Masking properties of a serialized object

### ISSUE THREAD

**Issue by forrestab** [serilog-contrib/Serilog.Enrichers.Sensitive#15]
We have a requirement to log the response body of each api request. There are a couple of fields in the response that are considered sensitive and need to be masked. I tried using `options.MaskProperties`, but that didn't seem to work and looks to be more for the placeholders in a message template.

Would something like this be achievable with this package? I considered creating a custom operator and using a combination of JsonPath to search and JsonPatch to replace, but not sure thats the best approach. Am I missing any combination of provide options?

Thanks.

**Comment by sandermvanvliet** [comment]
Can you give me an example of what the log message would look like?

If I understand it correctly you want to do something like:

```csharp
logger.Information(“Response body: {Response}”, serialisedResponseAsJson);
```
and the serialised response as:

```javascript
{
   “prop”: “super sensitive stuff”
}
```

with the result being that “super sensitive stuff” is masked?

**Comment by forrestab** [comment]
Yes except we are using serilog to do the serializing, i.e. 

```
logger.Information("Response body: {@Response}", response);
```

**Comment by sandermvanvliet** [comment]
Ah right, so you're using _destructured objects_.
In that case masking _should_ work actually as you can see in this test: [WhenMaskingDestructredObject](https://github.com/serilog-contrib/Serilog.Enrichers.Sensitive/blob/master/test/Serilog.Enrichers.Sensitive.Tests.Unit/WhenMaskingDestructuredObject.cs)

**Comment by sandermvanvliet** [comment]
Ok so I've added a test to specifically check for this use case, see [here](https://github.com/serilog-contrib/Serilog.Enrichers.Sensitive/blob/cbef705219b43b82a2e9dcd26814d20f808a2158/test/Serilog.Enrichers.Sensitive.Tests.Unit/WhenMaskingDestructuredObject.cs#L94) and that seems to work fine.

If you're seeing different results, could you create a repro case for me so that I can investigate?

**Comment by forrestab** [comment]
Im sorry I should have given you more information. You are correct masking does occur in destructured objects, but not in arrays.

I following sample is what Im trying to log and mask properties from:

```
{
    "items": [
        {
            "contactInfo": {
                "primary": {
                    "ssn": 0
                }
            }
        }
    ],
    "currentPage": 1
}
```

Im able to mask `currentPage`, but unable to mask `ssn` in the above json. 

However, if the object is not in an array, the `ssn` property is masked correctly. Ive also tried returning just an array of account objects and the `ssn` property was not masked. So it seems something doesn't like arrays.

**Comment by sandermvanvliet** [comment]
Thanks for the repro case. Let me have a quick look, shouldn’t be difficult to address this 👍

**Comment by sandermvanvliet** [comment]
That was indeed not very difficult, it's now released as [1.5.0](https://github.com/serilog-contrib/Serilog.Enrichers.Sensitive/releases/tag/1.5.0.0) and should be available through NuGet shortly after it has updated its index.

**Comment by forrestab** [comment]
Thank you, this is working perfectly!

**Comment by jeeby** [comment]
I'm having a very similar issue to this one.. when trying to mask certain properties in a json payload, it's only masking the email field. No matter what I try, only the email field gets masked.

Payload looks like this (after masking):
`{"FirstName":"Greg","LastName":"Berlin","Email":"******","LocationCode":"M010","ItemCodes":["I-025400"]}`

This is my config:
```
    "Enrich": [
      {
        "Name": "WithSensitiveDataMasking",
        "Args": {
          "options": {
            "MaskValue": "******",
            "MaskProperties": [
              "FirstName",
              "LastName",
              "Email"
            ],
            "Mode": "Globally"
          }
        }
      }
    ]
```

I've tried having just a single MaskProperty instead of 3 of them, but still only email gets masked (even when I specify `FirstName` for example.

Any ideas what I'm doing wrong? Is this supposed to work?  All your tests linked above only have a single field being masked, can you do one with more than 1 field?

Anything else I can try to get this working?

Thanks
